Vacation_Manager/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'trips#index'
  
  resources :trips do
    resources :locations
  end

  resources :locations do
    resources :addresses
  end

end

Vacation_Manager/app/models/address.rb
class Address < ApplicationRecord
  belongs_to :location
end

Vacation_Manager/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

 
 
 
 
 
 
 
   
end

Vacation_Manager/app/models/location.rb
class Location < ApplicationRecord
  belongs_to :trip
  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address
end

Vacation_Manager/app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :locations, dependent: :destroy
end

Vacation_Manager/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :trips
end

Vacation_Manager/app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, :set_location, :set_location_address

  def index

  end

  def show
  end

  def edit
    render :edit
  end

  def update
    if @address.update(address_params)
      redirect_to location_addresses_path(@location)
    else
      render :edit
    end
  end

  def new
    @address = @location.create_address()
  end

  def create
    @address = @location.create_address(params[:address])
    if @address.save
      redirect_to location_addresses_path(@location)
    else
      render :new
    end
  end

  def destroy
    @address.destroy
    redirect_to location_addresses_path(@location)
  end

  private
  def set_location
    @location = Location.find(params[:location_id])
  end

  def set_address
    @address = Address.create(params[:address])
  end

  def set_location_address
    @location.address = @address
  end

  def address_params
    params.require(:address).permit(:name, :street, :city, :state, :zip)
  end

end

Vacation_Manager/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
  
end

Vacation_Manager/app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_trip
  before_action :set_location, only:[:show, :edit, :update, :destroy]
  
  def index
    @locations = @trip.locations
  end

  def show
  end

  def new
    @location = @trip.locations.new()
    @location.build_address
  end

  def create
    add_atts = params[:location][:address_attributes]
    @location = @trip.locations.new(location_params)
    if @location.save
      a = @location.create_address(street: add_atts[:street], city: add_atts[:city], state: add_atts[:state], zip: add_atts[:zip])
      # binding.pry
      redirect_to trip_locations_path(@trip)
    else
      render :new
    end
  end

  def edit
    @location.build_address if @location.address.nil?
  end

  def update
    if @location.update(location_params)
      redirect_to trip_locations_path(@trip)
    else 
      render :edit
    end
  end

  def destroy
    @location.destroy
    redirect_to trip_locations_path(@trip)
  end

  private
  def set_trip
    @trip = Trip.find(params[:trip_id])
  end

  def set_location
    @location = Location.find(params[:id])
  end

  def location_params
    params.require(:location).permit(:name, :days)
  end
  


end

Vacation_Manager/app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only:[:show, :edit, :update, :destroy]
  
  def index
    
    @trips = current_user.trips
  end

  def show
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = current_user.trips.new(trip_params)
    if @trip.save
      redirect_to trips_path
    else
      :new
    end
  end

  def edit
  end

  def update
    if @trip.update(trip_params)
      redirect_to trips_path
    else
      :new
    end
  end

  def destroy
    @trip.destroy
    redirect_to trips_path
  end

  private
 def trip_params
   params.require(:trip).permit(:name, :user_id, :image)
 end

 def set_trip
   @trip = current_user.trips.find(params[:id])
 end

end

Vacation_Manager/app/helpers/addresses_helper.rb
module AddressesHelper
end

Vacation_Manager/app/helpers/application_helper.rb
module ApplicationHelper
end

Vacation_Manager/app/helpers/locations_helper.rb
module LocationsHelper
end

Vacation_Manager/app/helpers/trips_helper.rb
module TripsHelper
end

Vacation_Manager/app/views/addresses/_form.html.erb
<h1><%= @location.id ? 'Edit Address' : 'Create Address' %></h1>
<%= form_with [@address] do |f| %>
  <%= f.label :name %>
  <%= f.text_area :name, placeholder: "Name Of Address", class: "input" %>
  <br />
  <%= f.label :street %>
  <%= f.text_area :street, placeholder: "Street Name", class: "input" %>
  <br />
  <%= f.label :city %>
  <%= f.text_area :city, placeholder: "City Name", class: "input" %>
  <br />
  <%= f.label :state %>
  <%= f.text_area :state, placeholder: "State Name", class: "input" %>
  <br />
  <%= f.label :zip %>
  <%= f.text_field :zip, placeholder: 'Zippity' %>
  <br />
  <%= f.submit nil, class: "ui button green" %>
  <%end%>



  

Vacation_Manager/app/views/addresses/edit.html.erb
<h1>Addresses.:.Edit</h1>

<%= render "form" %>

Vacation_Manager/app/views/addresses/index.html.erb
<% if @location.address %>
  <h1>You have no addresses.</h1>
  <%= link_to "Add Your First Address", new_location_address_path(@location), class: "ui button green inverted"%>
  <%= link_to "Back To Locations", trip_locations_path(@location.trip_id), class: "ui button secondary inverted"%>
<% else %>
<h1>Showing Addresses for Location: <%= @location.name %> </h1>
  <%= link_to "Add Another Address", new_location_address_path(@location), class: "ui button green inverted"%>
  <%= link_to "Back To Locations", trip_locations_path(@location.trip_id), class: "ui button secondary inverted"%>
<hr />

<div class="ui cards">
  <div class="card">
    <div class="content">
      <div class="header">
        <%= address.name.upcase %>
      </div>
      <div class="meta">
        Meta data can go here
      </div>
      <div class="description">
        <%= @location.address.street %>
        <%= @location.address.city %>
        <%= @location.address.state%>
        <%= @location.address.zip%>
      </div>
    </div>
    <div class="content">
    <%= link_to "Remove Location", trip_location_path(@trip, location),method: :delete, class: "ui mini button red inverted"%>
    <%= link_to "Edit Location", edit_trip_location_path(@trip, location), class: "ui mini button secondary inverted"%>
    </div>
  </div>
</div>

<% end %>

Vacation_Manager/app/views/addresses/new.html.erb
<%= render "form" %>

Vacation_Manager/app/views/addresses/show.html.erb
<h1>Addresses#show</h1>
<p>Find me in app/views/addresses/show.html.erb</p>

Vacation_Manager/app/views/layouts/_navbar.html.erb
<div class="ui big secondary menu">
  <i class="huge blue suitcase icon"></i>

  <% if current_user %>
    <%= link_to "Home", trips_path, class: "item" %>
    <div class="right menu">
      <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"item" %>
    </div>
  <% end %>
</div>

Vacation_Manager/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hackathon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class = "ui container space">
      <%= render "layouts/navbar" %>
      <%= yield %>
    </div>
  </body>
</html>

Vacation_Manager/app/views/locations/_form.html.erb
<%= form_with(model: [@trip, @location], local: true, class: "ui form") do |f| %>
  <div class = "field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, autofocus: true, class: "input" %>
  </div>
    <%= f.label :days %>
    <%= f.text_field :days, class: "input" %>

    <%= f.fields_for :address do |fact| %>
      <%= fact.label :street %>
      <%= fact.text_field :street, class: "input" %>

      <%= fact.label :city %>
      <%= fact.text_field :city, class: "input" %>

      <%= fact.label :state %>
      <%= fact.text_field :state, class: "input" %>

      <%= fact.label :zip %>
      <%= fact.text_field :zip, class: "input" %>
  <% end %>

  <%= f.submit nil, class: "ui button green inverted"%>
  <% end %>

Vacation_Manager/app/views/locations/edit.html.erb
<h1>Edit This Location</h1>
<hr />
<%= render "form" %>

Vacation_Manager/app/views/locations/index.html.erb
<% if @trip.locations.length == 0 %>
  <h1>You have no locations planned.</h1>
  <%= link_to "Add Your First Location", new_trip_location_path(@trip), class: "ui button green inverted"%>
  <%= link_to "Back To Trips", trips_path, class: "ui button secondary inverted"%>
<% else %>
<h1>Showing Locations for <%= @trip.name %> </h1>
  <%= link_to "Add Another Location", new_trip_location_path(@trip), class: "ui button green inverted"%>
  <%= link_to "Back To Trips", trips_path, class: "ui button secondary inverted"%>
<hr />

<div class="ui cards">
<% @trip.locations.each do |location|%>
  <div class="teal card">
    <div class="content">
      <div class="header">
        <%= location.name.upcase %>
      </div>
      <div class="meta">
        Spending <%= location.days %> days here.
      </div>
      <div class="description">
        <%= location.address.street %>
        <%= location.address.city %><br />
        <%= location.address.state %><br />
        <%= location.address.zip %><br />
      </div>
    </div>
    <div class="content">
      <%= link_to "Edit Location", edit_trip_location_path(@trip, location), class: "ui mini button secondary inverted"%>
      <%= link_to "Remove Location", trip_location_path(@trip, location),method: :delete, class: "ui mini button red inverted"%>
    </div>
  </div>
<% end %>
</div>

<% end %>

Vacation_Manager/app/views/locations/new.html.erb
<h1>Add A Location</h1>
<hr />
<%= render "form" %>

Vacation_Manager/app/views/locations/show.html.erb
<h1>Locations#show</h1>
<p>Find me in app/views/locations/show.html.erb</p>

Vacation_Manager/app/views/trips/_form.html.erb
<%= form_with(model: @trip, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name Of Trip" %>
</div>
<div class="field">
    <%= f.label :image %>
    <%= f.text_field :image, placeholder: "Enter Image URL" %>
</div>  

<%= f.submit nil, class: "ui tiny button green inverted" %>
<%= link_to 'Back', trips_path, class: "ui tiny button secondary inverted" %>
<% end %>

Vacation_Manager/app/views/trips/edit.html.erb
<h1>Edit Your Trip</h1>
<hr>
<%= render "form" %>

Vacation_Manager/app/views/trips/index.html.erb
<% if current_user.trips == 0 %>
 <h1>You have no locations planned.</h1>
 <%= link_to "Add Your First Trip", new_trip_path(current_user.id), class: "ui button green inverted"%>
<% else %>
    <h1> Your Trips </h1>
    <%= link_to "Add A Trip", new_trip_path(current_user.id), class: "ui button green inverted"%>
    <hr>
    <br />
    <div class='ui centered stackable cards grid'>
        <% @trips.each do |trip|%>
            <div class="ui card">
                <div class="ui image">
                    <img src=<%= trip.image%> >
                </div>
                <div class="content">
                    <h2 class="header"> <%= link_to trip.name %></h2>
                </div>
                <div class="extra content">
                    <%= link_to 'See Locations', trip_locations_path(trip.id), class: 'ui tiny green button inverted'%>
                    <%= link_to 'Edit Trip', edit_trip_path(trip.id), class: 'ui tiny secondary button inverted' %>
                    <br />
                    <br />
                    <%= link_to 'Delete Trip', trip_path(trip.id), method: :delete, class: 'ui tiny red inverted button'  %>
                </div>
            </div>
        <%end%>
    </div>
<% end %>
    

Vacation_Manager/app/views/trips/new.html.erb
<h1>Add A New Trip</h1>
<hr>
<%= render "form" %>

Vacation_Manager/app/views/trips/show.html.erb
<h1>Trips#show</h1>
<p>Find me in app/views/trips/show.html.erb</p>